---
# kitchen configuration for CI testing
driver:
  name: docker

# Special config for enabling systemd init
default_driver_config: &default_driver_config
  run_command: /sbin/init
  cap_add:
    - SYS_ADMIN
  run_options:
    env: container=docker
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup
  provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
    - systemctl enable sshd.service

transport:
  # TODO: remove with better solution than workaround:
  # https://github.com/test-kitchen/test-kitchen/issues/1035
  max_ssh_sessions: 6

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: true
  requirements_path: test/requirements-test.yml

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      <<: *default_driver_config
  - name: ubuntu-16.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: ubuntu-18.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: debian-8
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: debian-9
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service

suites:
  - name: gem_install
    provisioner:
      playbook: test/integration/install/gem_install/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/install/gem_install
  - name: package_install
    provisioner:
      playbook: test/integration/install/package_install/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/install/package_install
  - name: fluent_conf
    provisioner:
      playbook: test/integration/config/fluent_conf/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/fluent_conf
  - name: launch_tdagent_pkg
    provisioner:
      playbook: test/integration/launch/td_agent_pkg/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/launch/td_agent_pkg
  - name: launch_fluentd_gem
    provisioner:
      playbook: test/integration/launch/fluentd_gem/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/launch/fluentd_gem
