---
- name: Ensure existence of fluentd config directory
  file:
    path: "{{ conf.path|default(_config_dir) }}"
    state: directory
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_user }}"
  become: true
  tags:
    - config

- name: Copy fluentd configuration in place
  template:
    src: "fluent.conf.j2"
    dest: "{{ conf.path|default(_config_dir) }}/{{ conf.name|default(_config_file) }}"
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_user }}"
    mode: 0644
    backup: true
  vars:
    directives: "{{ conf.directives }}"
  become: true
  when: conf.directives is defined and conf.directives|length > 0
  notify:
    - restart service
  tags:
    - config
