---
- name: Install list of Fluentd plugins
  command: "{{ _exe_path }}/{{ _plugin_exe }} install {{ item.name }}{{ ' -v ' + item.version if ('version' in item) else '' }}"
  loop: "{{ plugins }}"
  when: plugins is defined and plugins is not none
  notify:
    - restart service
