---
- name: Determine configuration directory
  set_fact:
    _config_dir: '/etc/td-agent'
  when: install_type == 'package'

- name: Determine configuration file name
  set_fact:
    _config_file: 'td-agent.conf'
  when: install_type == 'package'

- name: Determine service name
  set_fact:
    _service_name: 'td-agent'
  when: install_type == 'package'

- name: Set Fluentd unit [Service] configuration
  set_fact:
    _default_service_unit:
      ExecStart: "{{ _exe_path }}/{{ _service_name }} -c {{ _config_dir }}/{{ _config_file }} {{ extra_run_args|join(' ') }}"
      User: "{{ fluentd_user }}"
      Group: "{{ fluentd_user }}"
      StandardOutput: journal
      StandardError: inherit
  when: install_type == 'gem'
  notify:
    - reload service

- name: Determine plugin exe path
  set_fact:
    _exe_path: '/usr/sbin'
  when: install_type == 'package'

- name: Determine plugin exe
  set_fact:
    _plugin_exe: 'td-agent-gem'
  when: install_type == 'package'
