---
- name: Include OS and distribution specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true
  tags:
    - always

- name: Determine configuration directory
  set_fact:
    _config_dir: '/etc/td-agent'
  when: install_type == 'package'
  tags:
    - preflight

- name: Determine configuration file name
  set_fact:
    _config_file: 'td-agent.conf'
  when: install_type == 'package'
  tags:
    - preflight

- name: Determine service name
  set_fact:
    _service_name: 'td-agent'
  when: install_type == 'package'
  tags:
    - preflight

- name: Set Fluentd unit [Service] configuration
  set_fact:
    _default_service_unit:
      ExecStart: "{{ _exe_path }}/{{ _service_name }} -c {{ _config_dir }}/{{ _config_file }} {{ extra_run_args|join(' ') }}"
      User: "{{ fluentd_user }}"
      Group: "{{ fluentd_user }}"
      StandardOutput: journal
      StandardError: inherit
  when: install_type == 'gem'
  notify:
    - reload service
  tags:
    - preflight

- name: Determine plugin exe path
  set_fact:
    _exe_path: '/usr/sbin'
  when: install_type == 'package'
  tags:
    - preflight

- name: Determine plugin exe
  set_fact:
    _plugin_exe: 'td-agent-gem'
  when: install_type == 'package'
  tags:
    - preflight

- name: Check for uninstall signal
  block:
    - name: Broadcast uninstall signal
      command: /bin/true
      notify: Uninstall service

    - name: End play following uninstallation
      meta: end_play
  when: perform_uninstall
  ignore_errors: true
