---
- name: Determine configuration directory
  set_fact:
    config_dir: "{{ '/etc/td-agent' if install_type == 'package' else default_config_dir }}"

- name: Determine configuration file name
  set_fact:
    config_file: "{{ 'td-agent.conf' if install_type == 'package' else default_config_file }}"

- name: Determine service name
  set_fact:
    service_name: "{{ 'td-agent' if install_type == 'package' else default_service_name }}"

- name: Determine plugin exe path
  set_fact:
    exe_path: "{{ '/usr/sbin' if install_type == 'package' else default_exe_path }}"

- name: Determine plugin exe
  set_fact:
    plugin_exe: "{{ 'td-agent-gem' if install_type == 'package' else default_plugin_exe }}"
